# Generated by Django 5.2.4 on 2025-07-15 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_productview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductView',
        ),
    ]
