# Generated by Django 5.2.4 on 2025-07-17 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_address_alter_profile_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Format: +1234567890 or 1234567890', max_length=17),
        ),
        migrations.AlterField(
            model_name='profile',
            name='postal_code',
            field=models.CharField(blank=True, help_text='Format: 12345 or A1B 2C3', max_length=10),
        ),
    ]
